# Generated by Django 4.2.11 on 2025-05-20 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estatisticas', '0005_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='comentario_pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='estatisticas.comentario'),
        ),
    ]
